cvision/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from .views import HomePageView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'facedetection/', include(('facedetection.urls', 'facedetection'), namespace='facedetection')),
    path(r'supersampl/', include(('supersampl.urls', 'supersampl'), namespace='supersampl')),
    url(r'^$', HomePageView.as_view(), name='home')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facedetection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from .views import DetectFaceView, AddNewFaceView, StreamFaceView, StreamRawFaceView

urlpatterns = [
    url(r'^$', DetectFaceView.as_view(), name='recognize'),
    url(r'^raw-stream/$', StreamRawFaceView.as_view(), name='raw-stream'),
    url(r'^stream/$', StreamFaceView.as_view(), name='stream'),
    url(r'^add-face/$', AddNewFaceView.as_view(), name='add-face')
]

supersampl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from .views import GetImageView

urlpatterns = [
    url(r'^$', GetImageView.as_view(), name='get-image')
]

facedetection/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.


class EmbeddingsModel(models.Model):
    full_name = models.CharField(default='', max_length=100)
    embedding = ArrayField(ArrayField(models.FloatField(null=True, blank=True)))

supersampl/models.py
from django.db import models


class ImageModel(models.Model):
    image = models.ImageField(upload_to='images/')
    intermediate = models.ImageField(blank=True)
    processed = models.ImageField(blank=True)

facedetection/forms.py
from django import forms
from .models import EmbeddingsModel


class AddFaceForm(forms.ModelForm):
    full_name = forms.CharField(max_length=100, required=True)

    class Meta:
        model = EmbeddingsModel
        fields = ['full_name']

supersampl/forms.py
from django import forms
from .models import ImageModel


class UploadImageForm(forms.ModelForm):
    image = forms.ImageField(label='Choose a file', required=True, widget=forms.FileInput(
            attrs={"class": 'custom-file-input'}))

    class Meta:
        model = ImageModel
        fields = ['image']

cvision/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import CreateView


class HomePageView(CreateView):
    template_name = 'cvision/home.html'

    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, template_name=self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        context = {}
        return render(request, template_name=self.template_name, context=context)

facedetection/views.py
import time
import cv2
import numpy as np

from django.shortcuts import render, reverse, redirect
from django.views.generic import CreateView
from django.http import HttpResponse, StreamingHttpResponse

from facedetection.tf_face.recognition import FaceCV, RecognizeFace

from .forms import AddFaceForm
from .models import EmbeddingsModel

from cvision import settings

face_cv = FaceCV()
face_recon = RecognizeFace()

video = cv2.VideoCapture(0)


def raw_face_feed():
    while True:
        ret, frame = video.read()
        raw_face_feed.frame = frame
        frame = cv2.imencode('.jpg', frame)[1].tostring()
        yield (b'--frame\r\n' b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


def frame_feed():
    while True:
        ret, frame = video.read()
        frame = face_cv.analyze_frame(frame, include_body=settings.INCLUDE_BODY,
                                      skip_frames=settings.SKIP_FRAMES, include_identity=True)
        frame = cv2.imencode('.jpg', frame)[1].tostring()
        yield (b'--frame\r\n' b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')
        # time.sleep(0.05)


def read_video():
    with open(settings.VIDEO_PATH, 'rb') as file:
        bytes_video = file.read()
    return bytes_video


class AddNewFaceView(CreateView):
    template_name = 'facedetection/add_face.html'
    form_class = AddFaceForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {"form": form}
        return render(request, template_name=self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            model = form.save(commit=False)

            embedding = face_recon.create_embedding(raw_face_feed.frame)

            if embedding:
                model.embedding = embedding
                model.save()

            context = {}
            return render(request, template_name=self.template_name, context=context)
        return redirect(reverse('facedetection:add-face'))


class DetectFaceView(CreateView):
    template_name = 'facedetection/detect_face.html'

    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, template_name=self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        context = {}
        return render(request, template_name=self.template_name, context=context)


class StreamRawFaceView(CreateView):
    def get(self, request, *args, **kwargs):
        return StreamingHttpResponse(raw_face_feed(), 'multipart/x-mixed-replace; boundary=frame')


class StreamFaceView(CreateView):

    def get(self, request, *args, **kwargs):
        return StreamingHttpResponse(frame_feed(), 'multipart/x-mixed-replace; boundary=frame')

supersampl/views.py
import os
import cv2

from django.shortcuts import render, reverse, redirect
from django.views.generic import CreateView
from django.core.exceptions import ValidationError

from .forms import UploadImageForm
from .models import ImageModel
from cvision import settings
from .scale_cnn import DistilledResNetSR

keras_model = DistilledResNetSR()


class GetImageView(CreateView):
    template_name = 'supersampl/get_image.html'
    form_class = UploadImageForm

    def remove_files(self, path):
        for p in os.listdir(path):
            os.remove(os.path.join(path, p))

    def get(self, request, *args, **kwargs):
        self.remove_files(settings.ORIGINAL)
        self.remove_files(settings.INTERMEDIATE)
        self.remove_files(settings.PROCESSED)

        form = self.form_class()
        context = {"form": form}
        return render(request, template_name=self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            model = form.save(commit=True)

        full_image_path = model.image.path

        width, height = cv2.imread(full_image_path).shape[:2]

        if width > 1000 or height > 1000:
            context = {"form": form,
                       "error_message": "Image is too big. Image should be smaller than 1000x1000px"}

            return render(request, template_name=self.template_name, context=context)

        image_path = os.path.split(full_image_path)[1]
        intermediate = os.path.join(settings.INTERMEDIATE, image_path)
        end_path = os.path.join(settings.PROCESSED, image_path)

        keras_model.upscale(origin_path=full_image_path, intermediate=intermediate,
                            end_path=end_path, verbose=False)

        model.intermediate = os.path.join('intermediate', image_path)
        model.processed = os.path.join('processed', image_path)
        model.save()

        intermediate = model.intermediate.url
        processed = model.processed.url
        ImageModel.objects.all().delete()

        context = {"form": form,
                   "intermediate": intermediate,
                   "processed": processed}
        return render(request, template_name=self.template_name, context=context)

cvision/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif|Exo|Fjalla+One|Josefin+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Gentium+Basic|Hind+Siliguri|Mate|Radley" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    {% block head %}
    <title>Base</title>
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

cvision/templates/cvision/home.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block head %}
	{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/cvision/home.css' %}">
{% endblock %}

{% block body%}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'facedetection:recognize' %}">Detection</a>
                </li>


                <li class="nav-item">
                    <a class="nav-link" href="{% url 'supersampl:get-image' %}">Super Resolution</a>
                </li>
            </ul>
        </div>
    </nav>

    <section class="w3-container">


    <header class="w3-row">
             <div class="w3-col l5 m5">
                 <div class="w3-padding w3-center " style="margin-top: 170px;">
                     <h3 class="w3-jumbo">Face Detection</h3>
                     <p>Face detection in a continuous video stream in real time using neural networks.
                     In addition, the network is able to estimate the age and gender of the person detected.</p>
                 </div>
             </div>
             <div class="w3-col l7 m7" >
                 <div class="w3-padding">
                     <video src="{% static 'videos/demonstration.mp4' %}" autoplay loop width="auto"
                            style="max-height: 550px">
                     </video>
                 </div>
             </div>
    </header>
        <br>

    <main class="w3-row w3-margin-top">
        <div class="w3-col l4 m6 ">
            <div class="w3-margin"><img src="{% static 'images/colage.jpg' %}" width="100%">
            </div>
        </div>
        <br>
        <div class="w3-col l8 m6">
            <h3>About SR</h3>
            <hr>
            <p>Super Resolution is a neural network based algorithm which uses convolution over images to upscale the image
            with no quality loss and add details to make images sharper and remove digital noise</p></div>
    </main>

        </section>


{% endblock %}

facedetection/templates/facedetection/add_face.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block head %}
	{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/facedetection/add_face.css' %}">
{% endblock %}

{% block body%}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'facedetection:recognize' %}">Detection</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'supersampl:get-image' %}">Super Resolution</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="centered-block">
        <img src="{% url 'facedetection:raw-stream' %}" width="800px">
        <form method="POST">
            {% csrf_token %}
            <div class="input-form">
                <h6>Full name:</h6>
                {{ form.full_name }}
                <button class="btn btn-outline-success">Save</button>
            </div>
        </form>
    </div>

{% endblock %}

facedetection/templates/facedetection/detect_face.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block head %}
	{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/facedetection/detect_face.css' %}">
{% endblock %}

{% block body%}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'facedetection:recognize' %}">Detection</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'supersampl:get-image' %}">Super Resolution</a>
                </li>
            </ul>
        </div>
    </nav>


    <img id="stream" src="{% url 'facedetection:stream' %}" width="800px">
    <a href="{% url "facedetection:add-face" %}" class="btn btn-outline-success">Add Face</a>


{% endblock %}

supersampl/templates/supersampl/get_image.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block head %}
	{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/supersampl/get_image.css' %}">
{% endblock %}

{% block body%}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'facedetection:recognize' %}">Detection</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'supersampl:get-image' %}">Super Resolution</a>
                </li>
            </ul>
        </div>
    </nav>



    {% if intermediate %}
        <div class="container" id="comp">

            <div class="image">
                <img src="{{ intermediate }}" width="350">
                <div class="top-left"><h1 id="before">Before</h1></div>
            </div>

            <div class="image">
                <img src="{{ processed }}" width="350">
                <div class="top-left"><h1 id="after">After</h1></div>
            </div>

            <form class="md-form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="file-field big-2" id="choose-file">
                    <div class="btn btn-outline-danger btn-rounded waves-effect btn-lg float-left">
                        <label for="id_image">
                        <span>Choose file<i class="fas fa-upload ml-3" aria-hidden="true"></i></span>
                        </label>
                        {{ form.image }}
                    </div>
                </div>

                <button class="btn btn-outline-primary" id="submit-button">Submit</button>
            </form>

        </div>
    {% else %}

        <div class="container" id="comp">

            <div class="image">
                <img src="{% static 'images/tt23_raw.bmp' %}" width="350">
                <div class="top-left"><h1 id="before">Before</h1></div>
            </div>

            <div class="image">
                <img src="{% static 'images/tt23_processed.bmp' %}" width="350">
                <div class="top-left"><h1 id="after">After</h1></div>
            </div>

            {% if error_message %}
            <div class="alert alert-danger" role="alert">
              <strong>Oh snap!</strong> {{ error_message }}
            </div>
            {% endif %}

            <form class="md-form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="file-field big-2" id="choose-file">
                    <div class="btn btn-outline-danger btn-rounded waves-effect btn-lg float-left">
                        <label for="id_image">
                        <span>Choose file<i class="fas fa-upload ml-3" aria-hidden="true"></i></span>
                        </label>
                        {{ form.image }}
                    </div>
                </div>

                <button class="btn btn-outline-primary" id="submit-button">Submit</button>
            </form>

        </div>

    {% endif %}

{% endblock %}